<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "se_vat"
 *
 * Auto generated by Extension Builder 2019-03-02
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Users',
    'description' => 'Community features',
    'category' => 'plugin',
    'author' => '',
    'author_email' => '',
    'state' => 'alpha',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '0.1.0',
    'constraints' => [
        'depends' => [
            'typo3' => '8.7.0-8.7.99',
            't3helpers' => '0.9.5',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
